#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef VAULTSDK_SWIFT_H
#define VAULTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import PassKit;
@import UIKit;
@import WatchConnectivity;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VaultSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS("_TtC8VaultSDK20CampaignBasicDetails")
@interface CampaignBasicDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull endDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull companyId;
@property (nonatomic, readonly, copy) NSString * _Nonnull externalProgramId;
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly) NSInteger programId;
@property (nonatomic, readonly, copy) NSString * _Nonnull startDate;
@end

@class PKAddPaymentPassViewController;
@class NSData;
@class PKAddPaymentPassRequest;
@class PKPaymentPass;
SWIFT_CLASS("_TtC8VaultSDK52PassKitRepoitoryAddPaymentPassViewControllerDelegate")
@interface PassKitRepoitoryAddPaymentPassViewControllerDelegate : NSObject <PKAddPaymentPassViewControllerDelegate>
- (void)addPaymentPassViewController:(PKAddPaymentPassViewController * _Nonnull)controller generateRequestWithCertificateChain:(NSArray<NSData *> * _Nonnull)certificates nonce:(NSData * _Nonnull)nonce nonceSignature:(NSData * _Nonnull)nonceSignature completionHandler:(void (^ _Nonnull)(PKAddPaymentPassRequest * _Nonnull))completionHandler;
- (void)addPaymentPassViewController:(PKAddPaymentPassViewController * _Nonnull)controller didFinishAddingPaymentPass:(PKPaymentPass * _Nullable)pass error:(NSError * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TokenStatus, open) {
  TokenStatusActive = 0,
  TokenStatusUnmapped = 1,
  TokenStatusSuspended = 2,
  TokenStatusUnknown = 3,
};

@class NSCoder;
/// Native UIView subclass, holds VGSLabels.
SWIFT_CLASS("_TtC8VaultSDK23VGSCardFieldDisplayView")
@interface VGSCardFieldDisplayView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC8VaultSDK21VGSCardFieldPresenter")
@interface VGSCardFieldPresenter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum VaultSDKEnvironment : NSInteger;
@class VaultCardDisplayEntity;
@class UIViewController;
@class VaultCardModel;
enum VaultWalletDestination : NSInteger;
enum VaultWalletStatus : NSInteger;
SWIFT_CLASS("_TtC8VaultSDK11VPSVaultSDK")
@interface VPSVaultSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VPSVaultSDK * _Nonnull shared;)
+ (VPSVaultSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) enum VaultSDKEnvironment environment;
- (void)configureWithSubscriptionKey:(NSString * _Nonnull)subscriptionKey environment:(enum VaultSDKEnvironment)environment debug:(BOOL)debug applicationKeyId:(NSString * _Nullable)applicationKeyId applicationKeySecret:(NSString * _Nullable)applicationKeySecret;
- (void)setAuthenticationToken:(NSString * _Nonnull)token;
- (void)logout;
- (BOOL)isLoggedIn SWIFT_WARN_UNUSED_RESULT;
- (void)showCardNotPresentDetailsWithCardId:(NSInteger)cardId displayOptions:(VaultCardDisplayEntity * _Nonnull)displayOptions presentingViewController:(UIViewController * _Nonnull)presentingViewController;
- (void)getCampaignDetailsWithCard:(VaultCardModel * _Nonnull)card onComplete:(void (^ _Nonnull)(CampaignBasicDetails * _Nonnull))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)showUpdatePinWithCardId:(NSInteger)cardId displayOptions:(VaultCardDisplayEntity * _Nonnull)displayOptions presentingViewController:(UIViewController * _Nonnull)presentingViewController onComplete:(void (^ _Nonnull)(void))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)getWalletStatusWithCardId:(NSInteger)cardId forDevice:(enum VaultWalletDestination)device onComplete:(void (^ _Nonnull)(enum VaultWalletStatus))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)addCardToWalletWithCardId:(NSInteger)cardId cardName:(NSString * _Nonnull)cardName presentingViewController:(UIViewController * _Nonnull)presentingViewController onComplete:(void (^ _Nonnull)(void))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)updateMessagingToken:(NSString * _Nonnull)token card:(VaultCardModel * _Nonnull)card onComplete:(void (^ _Nonnull)(void))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)presentCardForPaymentWithCardId:(NSInteger)cardId onComplete:(void (^ _Nonnull)(void))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)resumeAddToWalletWithCardId:(NSInteger)cardId presentingViewController:(UIViewController * _Nonnull)presentingViewController onComplete:(void (^ _Nonnull)(void))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum VaultAccountState : NSInteger;
SWIFT_CLASS("_TtC8VaultSDK12VaultAccount")
@interface VaultAccount : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull externalAccountId;
@property (nonatomic, readonly) enum VaultAccountState status;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, readonly) BOOL compliant;
@property (nonatomic, readonly, copy) NSString * _Nullable nameOnCard;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountExpirationDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull plasticExpirationDate;
@property (nonatomic, readonly) BOOL isPlasticEnabled;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class VaultClient;
SWIFT_CLASS("_TtC8VaultSDK19VaultAccountDetails")
@interface VaultAccountDetails : NSObject
@property (nonatomic, readonly, strong) VaultAccount * _Nonnull account;
@property (nonatomic, readonly, strong) VaultClient * _Nullable client;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK26VaultAccountDetailsRequest")
@interface VaultAccountDetailsRequest : NSObject
@property (nonatomic, readonly) BOOL withClient;
@property (nonatomic, readonly) BOOL withFreeText;
@property (nonatomic, readonly, strong) VaultCardModel * _Nonnull card;
- (nonnull instancetype)initWithCard:(VaultCardModel * _Nonnull)card withClient:(BOOL)withClient withFreeText:(BOOL)withFreeText OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VaultAccountState, open) {
  VaultAccountStatePreActive = 1,
  VaultAccountStateActive = 2,
  VaultAccountStateInactive = 3,
  VaultAccountStateExpired = 4,
  VaultAccountStateClosed = 5,
  VaultAccountStateEmlInactive = 11,
  VaultAccountStateInactivePinTriesExceeded = 20,
  VaultAccountStateLostStolen = 31,
  VaultAccountStateSuspectedFraud = 32,
  VaultAccountStateDeactivated = 41,
  VaultAccountStateReplaced = 42,
  VaultAccountStateLocked = 43,
  VaultAccountStateUnknown = 0,
};

SWIFT_CLASS("_TtC8VaultSDK18VaultAccountStatus")
@interface VaultAccountStatus : NSObject
@property (nonatomic, readonly) enum VaultAccountState status;
@property (nonatomic, readonly, copy) NSString * _Nonnull externalAccountId;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull plasticExpirationDate;
@property (nonatomic, readonly) BOOL isPlasticEnabled;
@property (nonatomic, readonly, copy) NSString * _Nonnull mdesConfigId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK23VaultAccountStatusModel")
@interface VaultAccountStatusModel : NSObject
@property (nonatomic, readonly) enum VaultAccountState status;
@property (nonatomic, readonly, copy) NSString * _Nonnull externalAccountId;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull plasticExpirationDate;
@property (nonatomic, readonly) BOOL isPlasticEnabled;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK23VaultAccountTokensModel")
@interface VaultAccountTokensModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull panUniqueReference;
@property (nonatomic, readonly, copy) NSString * _Nonnull wallet;
@property (nonatomic, readonly) enum TokenStatus status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PKAddPaymentPassRequestConfiguration;
SWIFT_CLASS("_TtC8VaultSDK33VaultAddPaymentPassViewController")
@interface VaultAddPaymentPassViewController : PKAddPaymentPassViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithRequestConfiguration:(PKAddPaymentPassRequestConfiguration * _Nonnull)configuration delegate:(id <PKAddPaymentPassViewControllerDelegate> _Nullable)delegate SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC8VaultSDK12VaultAddress")
@interface VaultAddress : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable building;
@property (nonatomic, readonly, copy) NSString * _Nullable line1;
@property (nonatomic, readonly, copy) NSString * _Nullable line2;
@property (nonatomic, readonly, copy) NSString * _Nullable suburb;
@property (nonatomic, readonly, copy) NSString * _Nullable city;
@property (nonatomic, readonly, copy) NSString * _Nullable postcode;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK26VaultCardActivationRequest")
@interface VaultCardActivationRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull activationCode;
@property (nonatomic, readonly, strong) VaultCardModel * _Nonnull card;
- (nonnull instancetype)initWithCard:(VaultCardModel * _Nonnull)card activationCode:(NSString * _Nonnull)activationCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIImage;
@class NSURL;
@class UIColor;
SWIFT_CLASS("_TtC8VaultSDK22VaultCardDisplayEntity")
@interface VaultCardDisplayEntity : NSObject
@property (nonatomic, readonly, strong) UIImage * _Nullable cardImage;
@property (nonatomic, readonly, copy) NSURL * _Nullable cardImageURL;
@property (nonatomic, readonly, strong) UIColor * _Nonnull accentColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull cardForegroundTextColor;
- (nonnull instancetype)initWithCardImage:(UIImage * _Nullable)cardImage cardImageURL:(NSURL * _Nullable)cardImageURL accentColor:(UIColor * _Nonnull)accentColor cardForegroundTextColor:(UIColor * _Nonnull)cardForegroundTextColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum VaultProcessor : NSInteger;
SWIFT_CLASS("_TtC8VaultSDK14VaultCardModel")
@interface VaultCardModel : NSObject <NSCoding>
@property (nonatomic, copy) NSString * _Nonnull externalAccountId;
@property (nonatomic, copy) NSString * _Nonnull companyId;
@property (nonatomic, copy) NSString * _Nullable mdesConfigId;
@property (nonatomic) enum VaultProcessor processor;
- (nonnull instancetype)initWithExternalAccountId:(NSString * _Nonnull)externalAccountId companyId:(NSString * _Nonnull)companyId mdesConfigId:(NSString * _Nullable)mdesConfigId processor:(enum VaultProcessor)processor OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class VaultPassport;
SWIFT_CLASS("_TtC8VaultSDK11VaultClient")
@interface VaultClient : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable dateOfBirth;
@property (nonatomic, readonly, copy) NSString * _Nullable emailAddress;
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nullable mobileNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSString * _Nullable middleName;
@property (nonatomic, readonly, copy) NSString * _Nullable sex;
@property (nonatomic, readonly, copy) NSString * _Nullable driversLicenceNumber;
@property (nonatomic, readonly, strong) VaultAddress * _Nullable address;
@property (nonatomic, readonly, strong) VaultAddress * _Nullable alternateAddress;
@property (nonatomic, readonly, strong) VaultPassport * _Nullable passport;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class VaultTextModel;
@class VaultLinkModel;
SWIFT_CLASS("_TtC8VaultSDK17VaultConfigEntity")
@interface VaultConfigEntity : NSObject
@property (nonatomic, readonly) NSInteger minApiVersion;
@property (nonatomic, readonly) NSInteger termsVersion;
@property (nonatomic, readonly, copy) NSArray<VaultTextModel *> * _Nonnull terms;
@property (nonatomic, readonly, copy) NSArray<VaultTextModel *> * _Nonnull faqs;
@property (nonatomic, readonly, copy) NSArray<VaultLinkModel *> * _Nonnull supportLinks;
@property (nonatomic, readonly, copy) NSString * _Nullable supportTitle;
@property (nonatomic, readonly, copy) NSString * _Nullable playStoreUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable appStoreUrl;
@property (nonatomic, readonly) BOOL hideManagePin;
@property (nonatomic, readonly) BOOL isGiftCard;
@property (nonatomic, readonly, copy) NSString * _Nullable cardArtBaseUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum VaultDeactivationReasonCode : NSInteger;
SWIFT_CLASS("_TtC8VaultSDK26VaultDeactivateCardRequest")
@interface VaultDeactivateCardRequest : NSObject
@property (nonatomic) enum VaultDeactivationReasonCode reasonCode;
@property (nonatomic, strong) VaultCardModel * _Nonnull card;
- (nonnull instancetype)initWithCard:(VaultCardModel * _Nonnull)card reasonCode:(enum VaultDeactivationReasonCode)reasonCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VaultDeactivationReasonCode, open) {
  VaultDeactivationReasonCodeInactive = 0,
  VaultDeactivationReasonCodeClosedCancelled = 1,
  VaultDeactivationReasonCodeLostStolen = 2,
};

SWIFT_CLASS("_TtC8VaultSDK14VaultLinkModel")
@interface VaultLinkModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
@property (nonatomic, readonly, copy) NSString * _Nonnull destination;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
- (nonnull instancetype)initWithLabel:(NSString * _Nonnull)label destination:(NSString * _Nonnull)destination type:(NSString * _Nonnull)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK17VaultLoginRequest")
@interface VaultLoginRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull username;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic) BOOL keepLoggedIn;
- (nonnull instancetype)initWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password keepLoggedIn:(BOOL)keepLoggedIn OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK18VaultLoginResponse")
@interface VaultLoginResponse : NSObject
@property (nonatomic, copy) NSArray<VaultCardModel *> * _Nonnull cards;
@property (nonatomic, copy) NSString * _Nullable errorMessage;
- (nonnull instancetype)initWithCards:(NSArray<VaultCardModel *> * _Nonnull)cards errorMessage:(NSString * _Nullable)errorMessage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK28VaultManagePinDisplayRequest")
@interface VaultManagePinDisplayRequest : NSObject
- (nonnull instancetype)initWithCard:(VaultCardModel * _Nonnull)card displayOptions:(VaultCardDisplayEntity * _Nonnull)displayOptions OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK13VaultPassport")
@interface VaultPassport : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable number;
@property (nonatomic, readonly, copy) NSString * _Nullable issuingCountry;
@property (nonatomic, readonly, copy) NSString * _Nullable expiry;
- (nonnull instancetype)initWithNumber:(NSString * _Nullable)number issuingCountry:(NSString * _Nullable)issuingCountry expiry:(NSString * _Nullable)expiry OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK25VaultPasswordResetRequest")
@interface VaultPasswordResetRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable verificationCode;
@property (nonatomic, readonly, copy) NSString * _Nullable password;
- (nonnull instancetype)initWithPhoneNumber:(NSString * _Nonnull)phoneNumber verificationCode:(NSString * _Nullable)verificationCode password:(NSString * _Nullable)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK26VaultPasswordResetResponse")
@interface VaultPasswordResetResponse : NSObject
@property (nonatomic) BOOL codeRequired;
@property (nonatomic) BOOL passwordRequired;
@property (nonatomic, copy) NSArray<VaultCardModel *> * _Nullable cards;
- (nonnull instancetype)initWithCodeRequired:(BOOL)codeRequired passwordRequired:(BOOL)passwordRequired cards:(NSArray<VaultCardModel *> * _Nullable)cards OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK17VaultPinException")
@interface VaultPinException : NSObject
@property (nonatomic, readonly) BOOL cancelled;
@property (nonatomic, readonly) BOOL isUnauthorized;
@property (nonatomic, readonly) BOOL forceLogout;
- (nonnull instancetype)initWithStatusCode:(NSInteger)statusCode message:(NSString * _Nonnull)message cancelled:(BOOL)cancelled unauthorized:(BOOL)unauthorized forceLogout:(BOOL)forceLogout OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK29VaultPlasticActivationRequest")
@interface VaultPlasticActivationRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull activationCode;
@property (nonatomic, strong) VaultCardModel * _Nonnull card;
- (nonnull instancetype)initWithActivationCode:(NSString * _Nonnull)activationCode card:(VaultCardModel * _Nonnull)card OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VaultProcessor, open) {
  VaultProcessorAu = 0,
  VaultProcessorUs = 1,
};

SWIFT_CLASS("_TtC8VaultSDK26VaultRedeemGiftCardRequest")
@interface VaultRedeemGiftCardRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull activationCode;
@property (nonatomic, readonly, copy) NSString * _Nullable password;
- (nonnull instancetype)initWithPhoneNumber:(NSString * _Nonnull)phoneNumber activationCode:(NSString * _Nonnull)activationCode password:(NSString * _Nullable)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK27VaultRedeemGiftCardResponse")
@interface VaultRedeemGiftCardResponse : NSObject
@property (nonatomic, readonly) BOOL passwordRequired;
@property (nonatomic, readonly, copy) NSString * _Nullable accessToken;
@property (nonatomic, readonly, copy) NSArray<VaultCardModel *> * _Nullable cards;
@property (nonatomic, readonly, strong) VaultCardModel * _Nullable current;
- (nonnull instancetype)initWithPasswordRequired:(BOOL)passwordRequired accessToken:(NSString * _Nullable)accessToken cards:(NSArray<VaultCardModel *> * _Nullable)cards current:(VaultCardModel * _Nullable)current OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VaultSDKEnvironment, open) {
  VaultSDKEnvironmentDev = 0,
  VaultSDKEnvironmentBeta = 1,
  VaultSDKEnvironmentPreProd = 2,
  VaultSDKEnvironmentProd = 3,
};

SWIFT_CLASS("_TtC8VaultSDK37VaultShowCardNotPresentDetailsRequest")
@interface VaultShowCardNotPresentDetailsRequest : NSObject
@property (nonatomic, readonly, strong) VaultCardModel * _Nonnull card;
@property (nonatomic, readonly, strong) VaultCardDisplayEntity * _Nonnull displayOptions;
- (nonnull instancetype)initWithCard:(VaultCardModel * _Nonnull)card displayOptions:(VaultCardDisplayEntity * _Nonnull)displayOptions OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK14VaultTextModel")
@interface VaultTextModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSString * _Nonnull desc;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title desc:(NSString * _Nonnull)desc OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VaultWalletDestination, open) {
  VaultWalletDestinationEither = 0,
  VaultWalletDestinationWatch = 1,
  VaultWalletDestinationPhone = 2,
};

typedef SWIFT_ENUM(NSInteger, VaultWalletStatus, open) {
  VaultWalletStatusUnavailable = 0,
  VaultWalletStatusAvailable = 1,
  VaultWalletStatusAdded = 2,
  VaultWalletStatusRequiresVerification = 3,
};

@class WCSession;
SWIFT_CLASS("_TtC8VaultSDK30WatchRepositorySessionDelegate")
@interface WatchRepositorySessionDelegate : NSObject <WCSessionDelegate>
- (void)session:(WCSession * _Nonnull)session activationDidCompleteWithState:(WCSessionActivationState)activationState error:(NSError * _Nullable)error;
- (void)sessionDidBecomeInactive:(WCSession * _Nonnull)session;
- (void)sessionDidDeactivate:(WCSession * _Nonnull)session;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef VAULTSDK_SWIFT_H
#define VAULTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import PassKit;
@import UIKit;
@import WatchConnectivity;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VaultSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS("_TtC8VaultSDK20CampaignBasicDetails")
@interface CampaignBasicDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull endDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull companyId;
@property (nonatomic, readonly, copy) NSString * _Nonnull externalProgramId;
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly) NSInteger programId;
@property (nonatomic, readonly, copy) NSString * _Nonnull startDate;
@end

@class PKAddPaymentPassViewController;
@class NSData;
@class PKAddPaymentPassRequest;
@class PKPaymentPass;
SWIFT_CLASS("_TtC8VaultSDK52PassKitRepoitoryAddPaymentPassViewControllerDelegate")
@interface PassKitRepoitoryAddPaymentPassViewControllerDelegate : NSObject <PKAddPaymentPassViewControllerDelegate>
- (void)addPaymentPassViewController:(PKAddPaymentPassViewController * _Nonnull)controller generateRequestWithCertificateChain:(NSArray<NSData *> * _Nonnull)certificates nonce:(NSData * _Nonnull)nonce nonceSignature:(NSData * _Nonnull)nonceSignature completionHandler:(void (^ _Nonnull)(PKAddPaymentPassRequest * _Nonnull))completionHandler;
- (void)addPaymentPassViewController:(PKAddPaymentPassViewController * _Nonnull)controller didFinishAddingPaymentPass:(PKPaymentPass * _Nullable)pass error:(NSError * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TokenStatus, open) {
  TokenStatusActive = 0,
  TokenStatusUnmapped = 1,
  TokenStatusSuspended = 2,
  TokenStatusUnknown = 3,
};

@class NSCoder;
/// Native UIView subclass, holds VGSLabels.
SWIFT_CLASS("_TtC8VaultSDK23VGSCardFieldDisplayView")
@interface VGSCardFieldDisplayView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC8VaultSDK21VGSCardFieldPresenter")
@interface VGSCardFieldPresenter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum VaultSDKEnvironment : NSInteger;
@class VaultCardDisplayEntity;
@class UIViewController;
@class VaultCardModel;
enum VaultWalletDestination : NSInteger;
enum VaultWalletStatus : NSInteger;
SWIFT_CLASS("_TtC8VaultSDK11VPSVaultSDK")
@interface VPSVaultSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VPSVaultSDK * _Nonnull shared;)
+ (VPSVaultSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) enum VaultSDKEnvironment environment;
- (void)configureWithSubscriptionKey:(NSString * _Nonnull)subscriptionKey environment:(enum VaultSDKEnvironment)environment debug:(BOOL)debug applicationKeyId:(NSString * _Nullable)applicationKeyId applicationKeySecret:(NSString * _Nullable)applicationKeySecret;
- (void)setAuthenticationToken:(NSString * _Nonnull)token;
- (void)logout;
- (BOOL)isLoggedIn SWIFT_WARN_UNUSED_RESULT;
- (void)showCardNotPresentDetailsWithCardId:(NSInteger)cardId displayOptions:(VaultCardDisplayEntity * _Nonnull)displayOptions presentingViewController:(UIViewController * _Nonnull)presentingViewController;
- (void)getCampaignDetailsWithCard:(VaultCardModel * _Nonnull)card onComplete:(void (^ _Nonnull)(CampaignBasicDetails * _Nonnull))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)showUpdatePinWithCardId:(NSInteger)cardId displayOptions:(VaultCardDisplayEntity * _Nonnull)displayOptions presentingViewController:(UIViewController * _Nonnull)presentingViewController onComplete:(void (^ _Nonnull)(void))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)getWalletStatusWithCardId:(NSInteger)cardId forDevice:(enum VaultWalletDestination)device onComplete:(void (^ _Nonnull)(enum VaultWalletStatus))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)addCardToWalletWithCardId:(NSInteger)cardId cardName:(NSString * _Nonnull)cardName presentingViewController:(UIViewController * _Nonnull)presentingViewController onComplete:(void (^ _Nonnull)(void))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)updateMessagingToken:(NSString * _Nonnull)token card:(VaultCardModel * _Nonnull)card onComplete:(void (^ _Nonnull)(void))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)presentCardForPaymentWithCardId:(NSInteger)cardId onComplete:(void (^ _Nonnull)(void))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (void)resumeAddToWalletWithCardId:(NSInteger)cardId presentingViewController:(UIViewController * _Nonnull)presentingViewController onComplete:(void (^ _Nonnull)(void))onComplete onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum VaultAccountState : NSInteger;
SWIFT_CLASS("_TtC8VaultSDK12VaultAccount")
@interface VaultAccount : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull externalAccountId;
@property (nonatomic, readonly) enum VaultAccountState status;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, readonly) BOOL compliant;
@property (nonatomic, readonly, copy) NSString * _Nullable nameOnCard;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountExpirationDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull plasticExpirationDate;
@property (nonatomic, readonly) BOOL isPlasticEnabled;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class VaultClient;
SWIFT_CLASS("_TtC8VaultSDK19VaultAccountDetails")
@interface VaultAccountDetails : NSObject
@property (nonatomic, readonly, strong) VaultAccount * _Nonnull account;
@property (nonatomic, readonly, strong) VaultClient * _Nullable client;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK26VaultAccountDetailsRequest")
@interface VaultAccountDetailsRequest : NSObject
@property (nonatomic, readonly) BOOL withClient;
@property (nonatomic, readonly) BOOL withFreeText;
@property (nonatomic, readonly, strong) VaultCardModel * _Nonnull card;
- (nonnull instancetype)initWithCard:(VaultCardModel * _Nonnull)card withClient:(BOOL)withClient withFreeText:(BOOL)withFreeText OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VaultAccountState, open) {
  VaultAccountStatePreActive = 1,
  VaultAccountStateActive = 2,
  VaultAccountStateInactive = 3,
  VaultAccountStateExpired = 4,
  VaultAccountStateClosed = 5,
  VaultAccountStateEmlInactive = 11,
  VaultAccountStateInactivePinTriesExceeded = 20,
  VaultAccountStateLostStolen = 31,
  VaultAccountStateSuspectedFraud = 32,
  VaultAccountStateDeactivated = 41,
  VaultAccountStateReplaced = 42,
  VaultAccountStateLocked = 43,
  VaultAccountStateUnknown = 0,
};

SWIFT_CLASS("_TtC8VaultSDK18VaultAccountStatus")
@interface VaultAccountStatus : NSObject
@property (nonatomic, readonly) enum VaultAccountState status;
@property (nonatomic, readonly, copy) NSString * _Nonnull externalAccountId;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull plasticExpirationDate;
@property (nonatomic, readonly) BOOL isPlasticEnabled;
@property (nonatomic, readonly, copy) NSString * _Nonnull mdesConfigId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK23VaultAccountStatusModel")
@interface VaultAccountStatusModel : NSObject
@property (nonatomic, readonly) enum VaultAccountState status;
@property (nonatomic, readonly, copy) NSString * _Nonnull externalAccountId;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull plasticExpirationDate;
@property (nonatomic, readonly) BOOL isPlasticEnabled;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK23VaultAccountTokensModel")
@interface VaultAccountTokensModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull panUniqueReference;
@property (nonatomic, readonly, copy) NSString * _Nonnull wallet;
@property (nonatomic, readonly) enum TokenStatus status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PKAddPaymentPassRequestConfiguration;
SWIFT_CLASS("_TtC8VaultSDK33VaultAddPaymentPassViewController")
@interface VaultAddPaymentPassViewController : PKAddPaymentPassViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithRequestConfiguration:(PKAddPaymentPassRequestConfiguration * _Nonnull)configuration delegate:(id <PKAddPaymentPassViewControllerDelegate> _Nullable)delegate SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC8VaultSDK12VaultAddress")
@interface VaultAddress : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable building;
@property (nonatomic, readonly, copy) NSString * _Nullable line1;
@property (nonatomic, readonly, copy) NSString * _Nullable line2;
@property (nonatomic, readonly, copy) NSString * _Nullable suburb;
@property (nonatomic, readonly, copy) NSString * _Nullable city;
@property (nonatomic, readonly, copy) NSString * _Nullable postcode;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK26VaultCardActivationRequest")
@interface VaultCardActivationRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull activationCode;
@property (nonatomic, readonly, strong) VaultCardModel * _Nonnull card;
- (nonnull instancetype)initWithCard:(VaultCardModel * _Nonnull)card activationCode:(NSString * _Nonnull)activationCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIImage;
@class NSURL;
@class UIColor;
SWIFT_CLASS("_TtC8VaultSDK22VaultCardDisplayEntity")
@interface VaultCardDisplayEntity : NSObject
@property (nonatomic, readonly, strong) UIImage * _Nullable cardImage;
@property (nonatomic, readonly, copy) NSURL * _Nullable cardImageURL;
@property (nonatomic, readonly, strong) UIColor * _Nonnull accentColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull cardForegroundTextColor;
- (nonnull instancetype)initWithCardImage:(UIImage * _Nullable)cardImage cardImageURL:(NSURL * _Nullable)cardImageURL accentColor:(UIColor * _Nonnull)accentColor cardForegroundTextColor:(UIColor * _Nonnull)cardForegroundTextColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum VaultProcessor : NSInteger;
SWIFT_CLASS("_TtC8VaultSDK14VaultCardModel")
@interface VaultCardModel : NSObject <NSCoding>
@property (nonatomic, copy) NSString * _Nonnull externalAccountId;
@property (nonatomic, copy) NSString * _Nonnull companyId;
@property (nonatomic, copy) NSString * _Nullable mdesConfigId;
@property (nonatomic) enum VaultProcessor processor;
- (nonnull instancetype)initWithExternalAccountId:(NSString * _Nonnull)externalAccountId companyId:(NSString * _Nonnull)companyId mdesConfigId:(NSString * _Nullable)mdesConfigId processor:(enum VaultProcessor)processor OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class VaultPassport;
SWIFT_CLASS("_TtC8VaultSDK11VaultClient")
@interface VaultClient : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable dateOfBirth;
@property (nonatomic, readonly, copy) NSString * _Nullable emailAddress;
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nullable mobileNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSString * _Nullable middleName;
@property (nonatomic, readonly, copy) NSString * _Nullable sex;
@property (nonatomic, readonly, copy) NSString * _Nullable driversLicenceNumber;
@property (nonatomic, readonly, strong) VaultAddress * _Nullable address;
@property (nonatomic, readonly, strong) VaultAddress * _Nullable alternateAddress;
@property (nonatomic, readonly, strong) VaultPassport * _Nullable passport;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class VaultTextModel;
@class VaultLinkModel;
SWIFT_CLASS("_TtC8VaultSDK17VaultConfigEntity")
@interface VaultConfigEntity : NSObject
@property (nonatomic, readonly) NSInteger minApiVersion;
@property (nonatomic, readonly) NSInteger termsVersion;
@property (nonatomic, readonly, copy) NSArray<VaultTextModel *> * _Nonnull terms;
@property (nonatomic, readonly, copy) NSArray<VaultTextModel *> * _Nonnull faqs;
@property (nonatomic, readonly, copy) NSArray<VaultLinkModel *> * _Nonnull supportLinks;
@property (nonatomic, readonly, copy) NSString * _Nullable supportTitle;
@property (nonatomic, readonly, copy) NSString * _Nullable playStoreUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable appStoreUrl;
@property (nonatomic, readonly) BOOL hideManagePin;
@property (nonatomic, readonly) BOOL isGiftCard;
@property (nonatomic, readonly, copy) NSString * _Nullable cardArtBaseUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum VaultDeactivationReasonCode : NSInteger;
SWIFT_CLASS("_TtC8VaultSDK26VaultDeactivateCardRequest")
@interface VaultDeactivateCardRequest : NSObject
@property (nonatomic) enum VaultDeactivationReasonCode reasonCode;
@property (nonatomic, strong) VaultCardModel * _Nonnull card;
- (nonnull instancetype)initWithCard:(VaultCardModel * _Nonnull)card reasonCode:(enum VaultDeactivationReasonCode)reasonCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VaultDeactivationReasonCode, open) {
  VaultDeactivationReasonCodeInactive = 0,
  VaultDeactivationReasonCodeClosedCancelled = 1,
  VaultDeactivationReasonCodeLostStolen = 2,
};

SWIFT_CLASS("_TtC8VaultSDK14VaultLinkModel")
@interface VaultLinkModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
@property (nonatomic, readonly, copy) NSString * _Nonnull destination;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
- (nonnull instancetype)initWithLabel:(NSString * _Nonnull)label destination:(NSString * _Nonnull)destination type:(NSString * _Nonnull)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK17VaultLoginRequest")
@interface VaultLoginRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull username;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic) BOOL keepLoggedIn;
- (nonnull instancetype)initWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password keepLoggedIn:(BOOL)keepLoggedIn OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK18VaultLoginResponse")
@interface VaultLoginResponse : NSObject
@property (nonatomic, copy) NSArray<VaultCardModel *> * _Nonnull cards;
@property (nonatomic, copy) NSString * _Nullable errorMessage;
- (nonnull instancetype)initWithCards:(NSArray<VaultCardModel *> * _Nonnull)cards errorMessage:(NSString * _Nullable)errorMessage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK28VaultManagePinDisplayRequest")
@interface VaultManagePinDisplayRequest : NSObject
- (nonnull instancetype)initWithCard:(VaultCardModel * _Nonnull)card displayOptions:(VaultCardDisplayEntity * _Nonnull)displayOptions OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK13VaultPassport")
@interface VaultPassport : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable number;
@property (nonatomic, readonly, copy) NSString * _Nullable issuingCountry;
@property (nonatomic, readonly, copy) NSString * _Nullable expiry;
- (nonnull instancetype)initWithNumber:(NSString * _Nullable)number issuingCountry:(NSString * _Nullable)issuingCountry expiry:(NSString * _Nullable)expiry OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK25VaultPasswordResetRequest")
@interface VaultPasswordResetRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable verificationCode;
@property (nonatomic, readonly, copy) NSString * _Nullable password;
- (nonnull instancetype)initWithPhoneNumber:(NSString * _Nonnull)phoneNumber verificationCode:(NSString * _Nullable)verificationCode password:(NSString * _Nullable)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK26VaultPasswordResetResponse")
@interface VaultPasswordResetResponse : NSObject
@property (nonatomic) BOOL codeRequired;
@property (nonatomic) BOOL passwordRequired;
@property (nonatomic, copy) NSArray<VaultCardModel *> * _Nullable cards;
- (nonnull instancetype)initWithCodeRequired:(BOOL)codeRequired passwordRequired:(BOOL)passwordRequired cards:(NSArray<VaultCardModel *> * _Nullable)cards OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK17VaultPinException")
@interface VaultPinException : NSObject
@property (nonatomic, readonly) BOOL cancelled;
@property (nonatomic, readonly) BOOL isUnauthorized;
@property (nonatomic, readonly) BOOL forceLogout;
- (nonnull instancetype)initWithStatusCode:(NSInteger)statusCode message:(NSString * _Nonnull)message cancelled:(BOOL)cancelled unauthorized:(BOOL)unauthorized forceLogout:(BOOL)forceLogout OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK29VaultPlasticActivationRequest")
@interface VaultPlasticActivationRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull activationCode;
@property (nonatomic, strong) VaultCardModel * _Nonnull card;
- (nonnull instancetype)initWithActivationCode:(NSString * _Nonnull)activationCode card:(VaultCardModel * _Nonnull)card OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VaultProcessor, open) {
  VaultProcessorAu = 0,
  VaultProcessorUs = 1,
};

SWIFT_CLASS("_TtC8VaultSDK26VaultRedeemGiftCardRequest")
@interface VaultRedeemGiftCardRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull activationCode;
@property (nonatomic, readonly, copy) NSString * _Nullable password;
- (nonnull instancetype)initWithPhoneNumber:(NSString * _Nonnull)phoneNumber activationCode:(NSString * _Nonnull)activationCode password:(NSString * _Nullable)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK27VaultRedeemGiftCardResponse")
@interface VaultRedeemGiftCardResponse : NSObject
@property (nonatomic, readonly) BOOL passwordRequired;
@property (nonatomic, readonly, copy) NSString * _Nullable accessToken;
@property (nonatomic, readonly, copy) NSArray<VaultCardModel *> * _Nullable cards;
@property (nonatomic, readonly, strong) VaultCardModel * _Nullable current;
- (nonnull instancetype)initWithPasswordRequired:(BOOL)passwordRequired accessToken:(NSString * _Nullable)accessToken cards:(NSArray<VaultCardModel *> * _Nullable)cards current:(VaultCardModel * _Nullable)current OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VaultSDKEnvironment, open) {
  VaultSDKEnvironmentDev = 0,
  VaultSDKEnvironmentBeta = 1,
  VaultSDKEnvironmentPreProd = 2,
  VaultSDKEnvironmentProd = 3,
};

SWIFT_CLASS("_TtC8VaultSDK37VaultShowCardNotPresentDetailsRequest")
@interface VaultShowCardNotPresentDetailsRequest : NSObject
@property (nonatomic, readonly, strong) VaultCardModel * _Nonnull card;
@property (nonatomic, readonly, strong) VaultCardDisplayEntity * _Nonnull displayOptions;
- (nonnull instancetype)initWithCard:(VaultCardModel * _Nonnull)card displayOptions:(VaultCardDisplayEntity * _Nonnull)displayOptions OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8VaultSDK14VaultTextModel")
@interface VaultTextModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSString * _Nonnull desc;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title desc:(NSString * _Nonnull)desc OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VaultWalletDestination, open) {
  VaultWalletDestinationEither = 0,
  VaultWalletDestinationWatch = 1,
  VaultWalletDestinationPhone = 2,
};

typedef SWIFT_ENUM(NSInteger, VaultWalletStatus, open) {
  VaultWalletStatusUnavailable = 0,
  VaultWalletStatusAvailable = 1,
  VaultWalletStatusAdded = 2,
  VaultWalletStatusRequiresVerification = 3,
};

@class WCSession;
SWIFT_CLASS("_TtC8VaultSDK30WatchRepositorySessionDelegate")
@interface WatchRepositorySessionDelegate : NSObject <WCSessionDelegate>
- (void)session:(WCSession * _Nonnull)session activationDidCompleteWithState:(WCSessionActivationState)activationState error:(NSError * _Nullable)error;
- (void)sessionDidBecomeInactive:(WCSession * _Nonnull)session;
- (void)sessionDidDeactivate:(WCSession * _Nonnull)session;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
